name: Trigger auto deployment for container-app-kdjmvnbzyp7xo

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'fastify-api-server/**'
    - '.github/workflows/container-app-kdjmvnbzyp7xo-AutoDeployTrigger-bc0f6d95-b58e-4049-95c2-27b7ee36022d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPKDJMVNBZYP7XO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPKDJMVNBZYP7XO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPKDJMVNBZYP7XO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/fastify-api-server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPKDJMVNBZYP7XO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPKDJMVNBZYP7XO_REGISTRY_PASSWORD }}
          containerAppName: container-app-kdjmvnbzyp7xo
          resourceGroup: shopathomevue8fee
          imageToBuild: default/container-app-kdjmvnbzyp7xo:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


